// v3.2 – Goals Manager (fix nav + add/edit goals); keeps reports and circular KPIs
const USERS={'dominik@viewsk.com':{name:'Martin Dominik',role:'manager',pass:'viewadmin2025'},'lukac@viewsk.com':{name:'Róbert Lukáč',role:'sales',pass:'view2025'},'illesova@viewsk.com':{name:'Martina Illesová',role:'sales',pass:'view2025'}};
const REPORTS_KEY='v28_reports'; const GOALS_KEY='v30_goals';
function $(s){return document.querySelector(s)}; function $all(s){return Array.from(document.querySelectorAll(s))}
function currentUser(){const r=sessionStorage.getItem('vd_user');return r?JSON.parse(r):null}
function login(e,p){const u=USERS[e];if(!u)return{ok:false,msg:'Neexistujúci používateľ'};if(u.pass!==p)return{ok:false,msg:'Nesprávne heslo'};sessionStorage.setItem('vd_user',JSON.stringify({email:e,role:u.role,name:u.name}));return{ok:true}}
function logout(){sessionStorage.removeItem('vd_user');location.reload()}
function showToast(m='✅ Uložené'){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2000)}

function getReports(){const r=localStorage.getItem(REPORTS_KEY);return r?JSON.parse(r):{}}
function saveReports(o){localStorage.setItem(REPORTS_KEY,JSON.stringify(o))}
function getGoals(){const g=localStorage.getItem(GOALS_KEY);return g?JSON.parse(g):{}}
function saveGoals(d){localStorage.setItem(GOALS_KEY,JSON.stringify(d))}

function percent(a,t){if(!t||t<=0)return 0;return a/t*100}
function pctText(p){return (Math.round(p*10)/10).toFixed(1).replace('.',',')+' %'}
function pctColor(p){if(p>=100)return'#28a745';if(p>=50)return'#ff9800';return'#e11d48'}
function renderCircle(el,p){const size=140,r=62,cX=70,cY=70,circ=2*Math.PI*r,dash=Math.max(0,Math.min(circ,circ*(p/100)));el.innerHTML=`<svg width="${size}" height="${size}" viewBox="0 0 140 140"><circle cx="${cX}" cy="${cY}" r="${r}" fill="none" stroke="#eee" stroke-width="12"/><circle cx="${cX}" cy="${cY}" r="${r}" fill="none" stroke="${pctColor(p)}" stroke-width="12" stroke-linecap="round" transform="rotate(-90 ${cX} ${cY})" stroke-dasharray="${dash} ${circ-dash}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-size="20" fill="#333">${pctText(p)}</text></svg>`}
function renderMiniCircle(el,p){const size=80,r=30,cX=40,cY=40,circ=2*Math.PI*r,dash=Math.max(0,Math.min(circ,circ*(p/100)));el.innerHTML=`<svg width="${size}" height="${size}" viewBox="0 0 80 80"><circle cx="${cX}" cy="${cY}" r="${r}" fill="none" stroke="#eee" stroke-width="10"/><circle cx="${cX}" cy="${cY}" r="${r}" fill="none" stroke="${pctColor(p)}" stroke-width="10" stroke-linecap="round" transform="rotate(-90 ${cX} ${cY})" stroke-dasharray="${dash} ${circ-dash}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-size="12" fill="#333">${pctText(p)}</text></svg>`}

function setActiveMenu(route){$all('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.route===route))}
function showRoute(route){$all('.route').forEach(r=>r.classList.add('hidden'));const el=$('#route-'+route);if(el)el.classList.remove('hidden');setActiveMenu(route);if(route==='dashboard')renderDashboard();if(route==='reporty'){renderMyReports();renderAllReports()}if(route==='ciele')renderGoalsPage()}

function getISOWeek(d=new Date()){d=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const n=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-n);const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-y)/86400000)+1)/7)}
function getWeekRangeString(t=new Date()){const d=new Date(t),n=d.getDay()||7,m=new Date(d);m.setDate(d.getDate()-(n-1));const s=new Date(m);s.setDate(m.getDate()+6);const M=['januára','februára','marca','apríla','mája','júna','júla','augusta','septembra','októbra','novembra','decembra'];const f=x=>`${x.getDate()}. ${M[x.getMonth()]}`;return `${f(m)} – ${f(s)}`}
function checkMissingReport(email,wn){const d=getReports(),has=d[email]&&d[email][''+wn];$('#missingReportNotice').classList.toggle('hidden',!!has)}
function renderMyReports(){const c=currentUser();if(!c)return;const d=getReports(),m=d[c.email]||{},tb=$('#myReportsTable tbody');tb.innerHTML='';Object.keys(m).sort((a,b)=>+b-+a).forEach(w=>{const r=m[w],tr=document.createElement('tr');tr.innerHTML=`<td>${r.week}</td><td>${r.outreaches}</td><td>${r.meetingsAgreed}</td><td>${r.meetingsDone}</td><td>${r.offers}</td><td>${r.orders}</td>`;tb.appendChild(tr)})}
function renderAllReports(){const c=currentUser();if(!c||c.role!=='manager')return;const d=getReports(),tb=$('#allReportsTable tbody');tb.innerHTML='';Object.keys(d).forEach(e=>{const u=USERS[e],name=u?u.name:e;Object.keys(d[e]).sort((a,b)=>+b-+a).forEach(w=>{const r=d[e][w],tr=document.createElement('tr');if((r.orders||0)>=2)tr.classList.add('highlight');tr.innerHTML=`<td>${name}</td><td>${e}</td><td>${r.week}</td><td>${r.outreaches}</td><td>${r.meetingsAgreed}</td><td>${r.meetingsDone}</td><td>${r.offers}</td><td>${r.orders}</td>`;tb.appendChild(tr)})});$('#managerReportsWrap').classList.toggle('hidden',currentUser().role!=='manager')}
function saveReport(){const c=currentUser();if(!c){alert('Najprv sa prihlás');return}const w=($('#rWeek').value||'').trim(),o=+($('#rOutreaches').value||0),ma=+($('#rMeetingsAgreed').value||0),md=+($('#rMeetingsDone').value||0),of=+($('#rOffers').value||0),or=+($('#rOrders').value||0);if(!w){alert('Zadaj týždeň (číslo a rozsah v zátvorke).');return}const wn=parseInt(w,10)||getISOWeek(),d=getReports();d[c.email]=d[c.email]||{};d[c.email][''+wn]={week:w,outreaches:o,meetingsAgreed:ma,meetingsDone:md,offers:of,orders:or};saveReports(d);renderMyReports();renderAllReports();checkMissingReport(c.email,getISOWeek());showToast('✅ Report uložený')}

function renderDashboard(){const c=currentUser();if(!c)return;const g=getGoals();if(c.role==='manager'){let users=0,sumT=0,sumA=0;Object.keys(USERS).forEach(e=>{if(USERS[e].role!=='sales')return;const x=g[e];if(!x||(!x.target&&!x.actual))return;users++;sumT+=(+x.target||0);sumA+=(+x.actual||0)});const avg=users&&sumT>0?(sumA/sumT*100):0;$('#statUsers').textContent=users;$('#statTargets').textContent=(Math.round(sumT*10)/10).toLocaleString('sk-SK');$('#statActuals').textContent=(Math.round(sumA*10)/10).toLocaleString('sk-SK');$('#statAvg').textContent=pctText(avg);renderCircle($('#teamCircle'),isFinite(avg)?Math.max(0,Math.min(200,avg)):0);$('#managerSummary').classList.remove('hidden');$('#myGoalCard').classList.add('hidden')}else{const x=g[c.email]||{target:0,actual:0},p=percent(+x.actual||0,+x.target||0);$('#myTarget').textContent=(+x.target||0).toLocaleString('sk-SK');$('#myActual').textContent=(+x.actual||0).toLocaleString('sk-SK');$('#myPct').textContent=pctText(p);renderCircle($('#myCircle'),isFinite(p)?Math.max(0,Math.min(200,p)):0);$('#myGoalCard').classList.remove('hidden');$('#managerSummary').classList.add('hidden')}}

function renderGoalsPage(){const c=currentUser();if(!c)return;const g=getGoals();if(c.role==='manager'){ $('#addGoalCard').classList.remove('hidden'); const tb=$('#goalsTable tbody');tb.innerHTML='';['lukac@viewsk.com','illesova@viewsk.com'].forEach(e=>{const u=USERS[e],x=g[e]||{target:0,actual:0},p=percent(+x.actual||0,+x.target||0);const tr=document.createElement('tr');tr.innerHTML=`<td>${u.name}<br><small>${e}</small></td><td>${(+x.target||0).toLocaleString('sk-SK')}</td><td>${(+x.actual||0).toLocaleString('sk-SK')}</td><td>${pctText(p)}</td><td><div class="circle mini" id="mini_${e}"></div></td>`;tb.appendChild(tr);renderMiniCircle(document.getElementById('mini_'+e),p)});$('#managerGoals').classList.remove('hidden');$('#salesGoal').classList.add('hidden')}else{const x=g[c.email]||{target:0,actual:0},p=percent(+x.actual||0,+x.target||0);$('#sgTarget').textContent=(+x.target||0).toLocaleString('sk-SK');$('#sgActual').textContent=(+x.actual||0).toLocaleString('sk-SK');$('#sgPct').textContent=pctText(p);renderCircle($('#salesCircle'),isFinite(p)?Math.max(0,Math.min(200,p)):0);$('#managerGoals').classList.add('hidden');$('#salesGoal').classList.remove('hidden');$('#addGoalCard').classList.add('hidden')}}

function bindGoalForm(){const btn=$('#saveGoalBtn');if(!btn)return;btn.addEventListener('click',()=>{const email=$('#goalUser').value;const target=+($('#goalTarget').value||0);const actual=+($('#goalActual').value||0);const data=getGoals();data[email]={target,actual};saveGoals(data);showToast('✅ Cieľ uložený');renderGoalsPage();renderDashboard()})}

function bootSignedInUI(){const c=currentUser();if(!c)return;$('#appHeader').classList.remove('hidden');$('#appFooter').classList.remove('hidden');$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userLabel').textContent=c.name+' ('+c.email+')';$('#logoutBtn').classList.remove('hidden');$all('.only-manager').forEach(e=>e.classList.toggle('hidden',c.role!=='manager'));const wk=getISOWeek();const rng=getWeekRangeString();const weekInput=$('#rWeek');if(weekInput)weekInput.placeholder=`${wk} (${rng})`;checkMissingReport(c.email,wk);showRoute('dashboard')}

document.addEventListener('DOMContentLoaded',()=>{ $('#appHeader').classList.add('hidden');$('#appFooter').classList.add('hidden');$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden'); if(currentUser()) bootSignedInUI();
  $('#loginBtn').addEventListener('click',()=>{const email=$('#loginEmail').value.trim().toLowerCase();const pass=$('#loginPass').value.trim();const r=login(email,pass);if(!r.ok){alert(r.msg);return}bootSignedInUI()});
  $('#logoutBtn').addEventListener('click',()=>logout());
  $('#mainNav').addEventListener('click',(e)=>{const link=e.target.closest('[data-route]');if(!link)return;e.preventDefault();const cur=currentUser();if(!cur){alert('Najprv sa prihlás');return}const route=link.dataset.route;if(route==='obchodnici'&&cur.role!=='manager'){alert('Len pre manažéra');return}showRoute(route)});
  const hamburger=$('#hamburger'),nav=$('#mainNav');hamburger.addEventListener('click',()=>{const exp=hamburger.getAttribute('aria-expanded')==='true';hamburger.setAttribute('aria-expanded',String(!exp));nav.classList.toggle('show',!exp)});nav.addEventListener('click',(e)=>{if(e.target.closest('a')){hamburger.setAttribute('aria-expanded','false');nav.classList.remove('show')}});
  $('#saveReportBtn').addEventListener('click',saveReport);
  bindGoalForm();
});