// v3.0-goals-summary – kruhové grafy, ciele (v3.0) + reporty (v2.8)
const USERS={'dominik@viewsk.com':{name:'Martin Dominik',role:'manager',pass:'viewadmin2025'},'lukac@viewsk.com':{name:'Róbert Lukáč',role:'sales',pass:'view2025'},'illesova@viewsk.com':{name:'Martina Illesová',role:'sales',pass:'view2025'}};
const REPORTS_KEY='v28_reports';const GOALS_KEY='v30_goals';
function $(s){return document.querySelector(s)};function $all(s){return Array.from(document.querySelectorAll(s))}
function currentUser(){const r=sessionStorage.getItem('vd_user');return r?JSON.parse(r):null}
function login(e,p){const u=USERS[e];if(!u)return{ok:!1,msg:'Neexistujúci používateľ'};if(u.pass!==p)return{ok:!1,msg:'Nesprávne heslo'};sessionStorage.setItem('vd_user',JSON.stringify({email:e,role:u.role,name:u.name}));return{ok:!0}}
function logout(){sessionStorage.removeItem('vd_user');location.reload()}
function getReports(){const r=localStorage.getItem(REPORTS_KEY);return r?JSON.parse(r):{}}
function saveReports(o){localStorage.setItem(REPORTS_KEY,JSON.stringify(o))}
function getISOWeek(d=new Date()){d=new Date(Date.UTC(d.getFullYear(),d.getMonth(),d.getDate()));const n=d.getUTCDay()||7;d.setUTCDate(d.getUTCDate()+4-n);const y=new Date(Date.UTC(d.getUTCFullYear(),0,1));return Math.ceil((((d-y)/86400000)+1)/7)}
function getWeekRangeString(t=new Date()){const d=new Date(t),n=d.getDay()||7,m=new Date(d);m.setDate(d.getDate()-(n-1));const s=new Date(m);s.setDate(m.getDate()+6);const M=['januára','februára','marca','apríla','mája','júna','júla','augusta','septembra','októbra','novembra','decembra'];const f=x=>`${x.getDate()}. ${M[x.getMonth()]}`;return `${f(m)} – ${f(s)}`}
function showToast(m='✅ Uložené'){const t=$('#toast');t.textContent=m;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2000)}
function getGoals(){const g=localStorage.getItem(GOALS_KEY);return g?JSON.parse(g):{}}
function saveGoals(d){localStorage.setItem(GOALS_KEY,JSON.stringify(d))}
function percent(a,t){if(!t||t<=0)return 0;return a/t*100}
function pctText(p){return (Math.round(p*10)/10).toFixed(1).replace('.',',')+' %'}
function pctColor(p){if(p>=100)return'#28a745';if(p>=50)return'#ff9800';return'#e11d48'}
function renderCircle(el,p){const size=140,r=62,cX=70,cY=70,circ=2*Math.PI*r,dash=Math.max(0,Math.min(circ,circ*(p/100)));el.innerHTML=`<svg width="${size}" height="${size}" viewBox="0 0 140 140"><circle cx="${cX}" cy="${cY}" r="${r}" fill="none" stroke="#eee" stroke-width="12"/><circle cx="${cX}" cy="${cY}" r="${r}" fill="none" stroke="${pctColor(p)}" stroke-width="12" stroke-linecap="round" transform="rotate(-90 ${cX} ${cY})" stroke-dasharray="${dash} ${circ-dash}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-size="20" fill="#333">${pctText(p)}</text></svg>`}
function renderMiniCircle(el,p){const size=80,r=30,cX=40,cY=40,circ=2*Math.PI*r,dash=Math.max(0,Math.min(circ,circ*(p/100)));el.innerHTML=`<svg width="${size}" height="${size}" viewBox="0 0 80 80"><circle cx="${cX}" cy="${cY}" r="${r}" fill="none" stroke="#eee" stroke-width="10"/><circle cx="${cX}" cy="${cY}" r="${r}" fill="none" stroke="${pctColor(p)}" stroke-width="10" stroke-linecap="round" transform="rotate(-90 ${cX} ${cY})" stroke-dasharray="${dash} ${circ-dash}"/><text x="50%" y="50%" dominant-baseline="middle" text-anchor="middle" font-size="12" fill="#333">${pctText(p)}</text></svg>`}
function setActiveMenu(r){$all('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.route===r))}
function showRoute(r){$all('.route').forEach(e=>e.classList.add('hidden'));const el=$('#route-'+r);if(el)el.classList.remove('hidden');setActiveMenu(r)}
function renderDashboard(){const c=currentUser();if(!c)return;const g=getGoals();if(c.role==='manager'){let users=0,sumT=0,sumA=0;Object.keys(USERS).forEach(e=>{if(USERS[e].role!=='sales')return;const x=g[e];if(!x||(!x.target&&!x.actual))return;users++;sumT+=(+x.target||0);sumA+=(+x.actual||0)});const avg=users?(sumA/sumT*100):0;$('#statUsers').textContent=users;$('#statTargets').textContent=(Math.round(sumT*10)/10).toLocaleString('sk-SK');$('#statActuals').textContent=(Math.round(sumA*10)/10).toLocaleString('sk-SK');$('#statAvg').textContent=pctText(avg);renderCircle($('#teamCircle'),isFinite(avg)?Math.max(0,Math.min(200,avg)):0);$('#managerSummary').classList.remove('hidden');$('#myGoalCard').classList.add('hidden')}else{const x=g[c.email]||{target:0,actual:0},p=percent(+x.actual||0,+x.target||0);$('#myTarget').textContent=(+x.target||0).toLocaleString('sk-SK');$('#myActual').textContent=(+x.actual||0).toLocaleString('sk-SK');$('#myPct').textContent=pctText(p);renderCircle($('#myCircle'),isFinite(p)?Math.max(0,Math.min(200,p)):0);$('#myGoalCard').classList.remove('hidden');$('#managerSummary').classList.add('hidden')}}
function renderGoalsPage(){const c=currentUser();if(!c)return;const g=getGoals();if(c.role==='manager'){const tb=$('#goalsTable tbody');tb.innerHTML='';Object.keys(USERS).forEach(e=>{if(USERS[e].role!=='sales')return;const u=USERS[e],x=g[e]||{target:0,actual:0},p=percent(+x.actual||0,+x.target||0);const tr=document.createElement('tr');tr.innerHTML=`<td>${u.name}<br><small>${e}</small></td><td><input type="number" min="0" step="100" id="goal_t_${e}" value="${+x.target||0}"></td><td><input type="number" min="0" step="100" id="goal_a_${e}" value="${+x.actual||0}"></td><td>${pctText(p)}</td><td><div class="circle mini" id="mini_${e}"></div></td><td><button class="btn small" data-save="${e}">Uložiť</button></td>`;tb.appendChild(tr);renderMiniCircle(document.getElementById('mini_'+e),p)});tb.onclick=e=>{const b=e.target.closest('[data-save]');if(!b)return;const em=b.getAttribute('data-save'),t=+document.getElementById('goal_t_'+em).value||0,a=+document.getElementById('goal_a_'+em).value||0;const d=getGoals();d[em]={target:t,actual:a};saveGoals(d);showToast('✅ Ciele uložené');renderGoalsPage();renderDashboard()};$('#managerGoals').classList.remove('hidden');$('#salesGoal').classList.add('hidden')}else{const x=g[c.email]||{target:0,actual:0},p=percent(+x.actual||0,+x.target||0);$('#sgTarget').textContent=(+x.target||0).toLocaleString('sk-SK');$('#sgActual').textContent=(+x.actual||0).toLocaleString('sk-SK');$('#sgPct').textContent=pctText(p);renderCircle($('#salesCircle'),isFinite(p)?Math.max(0,Math.min(200,p)):0);$('#managerGoals').classList.add('hidden');$('#salesGoal').classList.remove('hidden')}}
function renderMyReports(){const c=currentUser();if(!c)return;const d=getReports(),m=d[c.email]||{},tb=$('#myReportsTable tbody');tb.innerHTML='';Object.keys(m).sort((a,b)=>+b-+a).forEach(w=>{const r=m[w],tr=document.createElement('tr');tr.innerHTML=`<td>${r.week}</td><td>${r.outreaches}</td><td>${r.meetingsAgreed}</td><td>${r.meetingsDone}</td><td>${r.offers}</td><td>${r.orders}</td>`;tb.appendChild(tr)})}
function renderAllReports(){const c=currentUser();if(!c||c.role!=='manager')return;const d=getReports(),tb=$('#allReportsTable tbody');tb.innerHTML='';Object.keys(d).forEach(e=>{const u=USERS[e],name=u?u.name:e;Object.keys(d[e]).sort((a,b)=>+b-+a).forEach(w=>{const r=d[e][w],tr=document.createElement('tr');if((r.orders||0)>=2)tr.classList.add('highlight');tr.innerHTML=`<td>${name}</td><td>${e}</td><td>${r.week}</td><td>${r.outreaches}</td><td>${r.meetingsAgreed}</td><td>${r.meetingsDone}</td><td>${r.offers}</td><td>${r.orders}</td>`;tb.appendChild(tr)})});$('#managerReportsWrap').classList.toggle('hidden',currentUser().role!=='manager')}
function saveReport(){const c=currentUser();if(!c){alert('Najprv sa prihlás');return}const w=($('#rWeek').value||'').trim(),o=+($('#rOutreaches').value||0),ma=+($('#rMeetingsAgreed').value||0),md=+($('#rMeetingsDone').value||0),of=+($('#rOffers').value||0),or=+($('#rOrders').value||0);if(!w){alert('Zadaj týždeň (číslo a rozsah v zátvorke).');return}const wn=parseInt(w,10)||getISOWeek(),d=getReports();d[c.email]=d[c.email]||{};d[c.email][''+wn]={week:w,outreaches:o,meetingsAgreed:ma,meetingsDone:md,offers:of,orders:or};saveReports(d);renderMyReports();renderAllReports();checkMissingReport(c.email,getISOWeek());showToast('✅ Report uložený')}
function checkMissingReport(e,wn){const d=getReports(),has=d[e]&&d[e][''+wn];$('#missingReportNotice').classList.toggle('hidden',!!has)}
function bootSignedInUI(){const c=currentUser();if(!c)return;$('#appHeader').classList.remove('hidden');$('#appFooter').classList.remove('hidden');$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userLabel').textContent=c.name+' ('+c.email+')';$('#logoutBtn').classList.remove('hidden');$all('.only-manager').forEach(x=>x.classList.toggle('hidden',c.role!=='manager'));const wk=getISOWeek();$('#welcomeCard').textContent='Vitaj späť, '+c.name+'!';checkMissingReport(c.email,wk);$('#rWeek').placeholder=`${wk} (${getWeekRangeString()})`;renderDashboard();showRoute('dashboard')}
document.addEventListener('DOMContentLoaded',()=>{$('#appHeader').classList.add('hidden');$('#appFooter').classList.add('hidden');$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');if(currentUser())bootSignedInUI();$('#loginBtn').onclick=()=>{const e=$('#loginEmail').value.trim().toLowerCase(),p=$('#loginPass').value.trim(),r=login(e,p);if(!r.ok){alert(r.msg);return}bootSignedInUI()};$('#logoutBtn').onclick=()=>logout();$('#mainNav').onclick=e=>{const l=e.target.closest('[data-route]');if(!l)return;e.preventDefault();const c=currentUser();if(!c){alert('Najprv sa prihlás');return}const r=l.dataset.route;if(r==='obchodnici'&&c.role!=='manager'){alert('Len pre manažéra');return}showRoute(r);if(r==='reporty'){renderMyReports();renderAllReports()}if(r==='ciele'){renderGoalsPage()}if(r==='dashboard'){renderDashboard()}};const hb=$('#hamburger'),nav=$('#mainNav');hb.onclick=()=>{const ex=hb.getAttribute('aria-expanded')==='true';hb.setAttribute('aria-expanded',String(!ex));nav.classList.toggle('show',!ex)};nav.onclick=e=>{if(e.target.closest('a')){hb.setAttribute('aria-expanded','false');nav.classList.remove('show')}};$('#saveReportBtn').onclick=()=>saveReport()});